# Generated by Django 5.2.1 on 2025-05-23 17:40

import datetime
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('supervisor', 'Supervisor'), ('project_leader', 'Project Leader')], max_length=20)),
                ('first_login_date', models.DateField(default=datetime.date.today)),
                ('job', models.CharField(blank=True, choices=[('software_engineer', 'Software Engineer'), ('data_scientist', 'Data Scientist'), ('devops_engineer', 'DevOps Engineer'), ('system_administrator', 'System Administrator'), ('product_manager', 'Product Manager'), ('ui_ux_designer', 'UI/UX Designer'), ('qa_engineer', 'QA Engineer'), ('business_analyst', 'Business Analyst'), ('security_specialist', 'Security Specialist'), ('network_engineer', 'Network Engineer')], max_length=30, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('first_login', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, choices=[('casablanca', 'Casablanca'), ('rabat', 'Rabat'), ('marrakech', 'Marrakech'), ('fes', 'Fès'), ('tanger', 'Tanger'), ('agadir', 'Agadir'), ('meknes', 'Meknès'), ('oujda', 'Oujda'), ('kenitra', 'Kénitra'), ('nador', 'Nador')], max_length=30, null=True)),
                ('profile_photo', models.ImageField(blank=True, default='profile_pictures/base_avatar.jpg', upload_to='profile_pictures', verbose_name='Profile Photo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_leaders', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
