# Generated by Django 5.2.1 on 2025-05-27 16:30

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_icons/')),
                ('start_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 5, 27))])),
                ('end_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 5, 27))])),
                ('client_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled'), ('deferred', 'Deferred'), ('archived', 'Archived')], default='not_started', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_leader', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 5, 27))])),
                ('end_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 5, 27))])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
        ),
    ]
